-- AlterTable
ALTER TABLE `documents` MODIFY `type` ENUM('PDF', 'DOCX', 'ZIP', 'PROPOSAL', 'INVOICE', 'SPREADSHEET', 'QUOTATION', 'RECEIPT', 'PURCHASE_ORDER', 'PROFORMA_INVOICE', 'CREDIT_NOTE', 'DEBIT_NOTE', 'AGREEMENT') NOT NULL,
    MODIFY `status` ENUM('DRAFT', 'REVIEW', 'COMPLETED', 'ARCHIVED', 'SENT', 'APPROVED', 'REJECTED', 'PAID', 'CANCELLED') NOT NULL DEFAULT 'DRAFT';

-- CreateTable
CREATE TABLE `document_versions` (
    `id` VARCHAR(191) NOT NULL,
    `documentId` VARCHAR(191) NOT NULL,
    `version` INTEGER NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `content` TEXT NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `document_versions` ADD CONSTRAINT `document_versions_documentId_fkey` FOREIGN KEY (`documentId`) REFERENCES `documents`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
